spring:
  datasource:
    username: root
    password: lzh123456
    #    mysql8 连接
    url: jdbc:mysql://127.0.0.1:3306/javatest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    #    mysql8 要加cj
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    #格式化
    date-format: yyyy-MM-dd hh:mm:ss
    #东八区
    time-zone: GMT+8
    # null字段不返回前端
    default-property-inclusion: non_null

#mybatis:
#  type-aliases-package: com.example.sample1.pojo
#  mapper-locations: classpath:/mapper/*.xml

logging:
  file:
    name: log/log.log
  level:
    root: info
    com.example.sample1: debug